version: '3.4'

networks:
  retail-dev:
    driver: bridge
  rabbitmq_net:
    driver: bridge

services:

  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    ports:
         - "8080:80"
    environment:
      - PostgresqlConnectionString=User ID=postgres;Password=postgres;Server=postgres;Port=5432;Database=SampleCategory;
    networks:
      - retail-dev
      - rabbitmq_net


  cartservice:
     image: ${DOCKER_REGISTRY-}cartservice
     depends_on:
      - "mongo"
     build:
       context: .
       dockerfile: CartService/Dockerfile
     ports:
         - "8081:80"
     environment:
       - MongoDbConnectionString=mongodb://mongo:27017/
     networks:
       - retail-dev
       - rabbitmq_net

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    depends_on:
      - "mongo"
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
        - "8082:80"
    environment:
      - MongoDbConnectionString=mongodb://mongo:27017/
    networks:
      - retail-dev
      - rabbitmq_net

  logservice:
    image: ${DOCKER_REGISTRY-}logservice
    depends_on:
      - "mongo"
    build:
      context: .
      dockerfile: LogService/Dockerfile
    ports:
         - "8083:80"
    networks:
      - retail-dev
      - rabbitmq_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
        - rabbitmq_net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_volume:/var/lib/mongodb/data
    networks:
      - retail-dev


  postgres:
    image: postgres:latest
    ports:
        - "5433:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleCategory
    networks:
      - retail-dev


volumes:
  db_volume:

